config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'home/index'
  root "home#index"
  resources :divisions
  resources :targets
  resources :teams
  resources :employees
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/employee.rb
class Employee < ApplicationRecord
    belongs_to :division
    belongs_to :team
    validates :name, presence: true
    validates :email, presence: true
    validates :team_id, presence: true
    validates :division_id, presence: true
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  # GET /employees or /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1 or /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
    @divisionsIds = get_divisions_ids()
    @teamsIds = get_teams_ids()
  end

  # GET /employees/1/edit
  def edit
    @divisionsIds = get_divisions_ids()
    @teamsIds = get_teams_ids()
  end

  # POST /employees or /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully created." }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employee_url(@employee), notice: "Employee was successfully updated." }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(:employee).permit(:name, :email, :job, :salary, :employment_status, :division_id, :team_id)
    end

    def get_divisions_ids
      @divisions = Division.all
      @divisionsIds = []
      @divisions.each do |d|
        @divisionsIds.push(d.id)
      end
      return @divisionsIds
    end
    def get_teams_ids
      @teams = Team.all
      @teamsIds = []
      @teams.each do |d|
        @teamsIds.push(d.id)
      end
      return @teamsIds
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee.html.erb
<div id="<%= dom_id employee %>">
  <p>
    <strong><%= t 'Name', default: 'not exist'  %></strong>
    <%= employee.name %>
  </p>
  <p>
    <strong><%= t 'Email', default: 'not exist'  %></strong>
    <%= employee.email %>
  </p>

  <p>
    <strong><%= t 'Job', default: 'not exist'  %></strong>
    <%= employee.job %>
  </p>

  <p>
    <strong><%= t 'Salary', default: 'not exist'  %></strong>
    <%= employee.salary %>
  </p>

  <p>
    <strong><%= t 'Job status', default: 'not exist'  %></strong>
    <%= employee.employment_status %>
  </p>

  <p>
  <% if employee.team.present? %>
      <strong><%= t 'Team', default: 'not exist'  %></strong>
      <%= employee.team.name %>
    <% end %>
  </p>

  <p>
  <% if employee.division.present? %>
      <strong><%= t 'Division', default: 'not exist'  %></strong>
      <%= employee.division.name %>
    <% end %>
  </p>

</div>

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |form| %>
  <% if employee.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>
      
      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :job, style: "display: block" %>
    <%= form.text_field :job %>
  </div>

  <div>
    <%= form.label :salary, style: "display: block" %>
    <%= form.text_field :salary %>
  </div>

  <div>
    <%= form.label :employment_status, style: "display: block" %>
    <%= form.text_field :employment_status %>
  </div>


  <div>
   <%= form.label :team_id %>
   <%= form.select :team_id, Team.all.collect{ |team| ["#{team.name}",team.id] }, prompt: 'Choose one...' %>
 </div>


  <div>
   <%= form.label :division_id %>
   <%= form.select :division_id, Division.all.collect{ |division| ["#{division.name}",division.id] }, prompt: 'Choose one...' %>
 </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/_lists.html.erb
<p>----------------</p>
<h4>List of divisions</h4>
<div>
  <ul>
    <% @divisions.each do |division| %>
        <li>
          <%= division.id %><span> </span><%= division.name %>
        </li>
      <% end %>
   </ul>
</div>
<h4>List of teams</h4>
<div>
  <ul>
    <% @teams.each do |team| %>
        <li>
          <%= team.id %><span> </span><%= team.name %>
        </li>
      <% end %>
   </ul>
</div>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render "form", employee: @employee, divisionsIds: @divisionsIds, teamsIds: @teamsIds %>
<%= render "lists"%>

<br>

<div>
  <%= link_to "Show this employee", @employee %> |
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Employees</h1>

<div class="btn btn-info newbtn">
<%= link_to "New employee", new_employee_path %>
</div>

<br>
<br>
<div id="employees">
<table class="table table-striped">
<thead>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Email</th>
    <th>Job</th>
    <th>Salary</th>
    <th>Team</th>
    <th>Status</th>
    <th>Action</th>
  </tr>
<tbody>

  <% @employees.each do |employee| %>
  <tr>
    <td><%= employee.id%></td>
    <td><%= employee.name%></td>
    <td><%= employee.email%></td>
    <td><%= employee.job%></td>
    <td><%= employee.salary%></td>
    <% if employee.team.present? == true %>
     <td><%= employee.team.name %></td>
    <% end %>
    <% if employee.team.present? == false %>
     <td><%=  %></td>
    <% end %>
    <td><%= employee.employment_status %></td>
    <td class="actions">
      <%= link_to "Edit", edit_employee_path(employee) %> 
      <%= button_to "Delete", employee, method: :delete %>
    </td>
  </tr>
  <% end %>
    </thead>
  </table>
</div>
<br>


<br>
<div class="btn">
<%= link_to "Back to home", "/" %>
</div>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render "form", employee: @employee, divisionsIds: @divisionsIds, teamsIds: @teamsIds%>

<br>

<div>
  <%= link_to "Back to employees", employees_path %>
</div>

app/views/employees/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @employee %>

<div>
  <%= link_to "Edit this employee", edit_employee_path(@employee) %> 
  <%= link_to "Back to employees", employees_path %>

  <%= button_to "Destroy this employee", @employee, method: :delete %>
</div>