config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'home/index'
  root "home#index"
  resources :divisions
  resources :targets
  resources :teams
  resources :employees
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/target.rb
class Target < ApplicationRecord
    belongs_to :team

    validates :title, presence: true
    validates :description, presence: true
    validates :start_date, presence: true
    validates :finish_date, presence: true
    validates :status, presence: true

    validate :end_date_is_after_start_date


#######
private
#######

    def end_date_is_after_start_date
        return if finish_date.blank? || start_date.blank?

        if finish_date < start_date
            errors.add(:finish_date, "cannot be before the start date") 
        end 
    end

end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :set_target, only: %i[ show edit update destroy ]

  # GET /targets or /targets.json
  def index
    @targets = Target.all
  end

  # GET /targets/1 or /targets/1.json
  def show
  end

  # GET /targets/new
  def new
    @target = Target.new
    @teamsIds = get_teams_ids()
  end

  # GET /targets/1/edit
  def edit
    @teamsIds = get_teams_ids()
  end

  # POST /targets or /targets.json
  def create
    @target = Target.new(target_params)

    respond_to do |format|
      if @target.save
        format.html { redirect_to target_url(@target), notice: "Target was successfully created." }
        format.json { render :show, status: :created, location: @target }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /targets/1 or /targets/1.json
  def update
    respond_to do |format|
      if @target.update(target_params)
        format.html { redirect_to target_url(@target), notice: "Target was successfully updated." }
        format.json { render :show, status: :ok, location: @target }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @target.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /targets/1 or /targets/1.json
  def destroy
    @target.destroy

    respond_to do |format|
      format.html { redirect_to targets_url, notice: "Target was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_target
      @target = Target.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def target_params
      params.require(:target).permit(:title, :description, :start_date, :finish_date, :status, :team_id)
    end
    def get_teams_ids
      @teams = Team.all
      @teamsIds = []
      @teams.each do |d|
        @teamsIds.push(d.id)
      end
      return @teamsIds
    end
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/targets/_form.html.erb
<%= form_with(model: target) do |form| %>
  <% if target.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(target.errors.count, "error") %> prohibited this target from being saved:</h2>

      <ul>
        <% target.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :finish_date, style: "display: block" %>
    <%= form.date_field :finish_date %>
  </div>

  <div>
    <%= form.label :status, style: "display: block" %>
    <%= form.text_field :status %>
  </div>

<div>
   <%= form.label :team_id %>
   <%= form.select :team_id, Team.all.collect{ |team| ["#{team.name}",team.id] }, prompt: 'Choose one...' %>
 </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/targets/_lists.html.erb
<p>----------------</p>
<h4>List of teams</h4>
<div>
  <ul>
    <% @teams.each do |team| %>
        <li>
          <%= team.id %><span> </span><%= team.name %>
        </li>
      <% end %>
   </ul>
</div>

app/views/targets/_target.html.erb
<div id="<%= dom_id target %>">
  <p>
    <strong>Title:</strong>
    <%= target.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= target.description %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= target.start_date %>
  </p>

  <p>
    <strong>Finish date:</strong>
    <%= target.finish_date %>
  </p>

  <p>
    <strong>Team:</strong>
    <%= target.team.name %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= target.status %>
  </p>

</div>

app/views/targets/edit.html.erb
<h1>Editing target</h1>

<%= render "form", target: @target, teamsIds: @teamsIds%>
<%= render "lists"%>
<br>

<div>
  <%= link_to "Show this target", @target %> |
  <%= link_to "Back to targets", targets_path %>
</div>

app/views/targets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Targets</h1>

<div class="btn btn-info newbtn">
<%= link_to "New target", new_target_path %>
</div>

<br>
<br>
<div id="targets">
<table class="table table-striped">
<thead>
  <tr>
    <th>Id</th>
    <th>Title</th>
    <th>Description</th>
    <th>Team</th>
    <th>Start Date</th>
    <th>Finish Date</th>
    <th>Status</th>
    <th>Action</th>
  </tr>
<tbody>

  <% @targets.each do |target| %>
  <tr>
    <td><%= target.id%></td>
    <td><%= target.title%></td>
    <td><%= target.description%></td>
    <td><%= target.team.name %></td>
    <td><%= target.start_date %></td>
    <td><%= target.finish_date %></td>
    <td><%= target.status %></td>
    <td class="actions">
      <%= link_to "Edit", edit_target_path(target) %> 
      <%= button_to "Delete", target, method: :delete %>
    </td>
  </tr>
  <% end %>
    </thead>
  </table>
</div>


<br>
<div class="btn">
<%= link_to "Back to home", "/" %>
</div>

app/views/targets/new.html.erb
<h1>New target</h1>

<%= render "form", target: @target, teamsIds: @teamsIds%>

<br>

<div>
  <%= link_to "Back to targets", targets_path %>
</div>

app/views/targets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @target %>

<div>
  <%= link_to "Edit this target", edit_target_path(@target) %> |
  <%= link_to "Back to targets", targets_path %>

  <%= button_to "Destroy this target", @target, method: :delete %>
</div>