config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'home/index'
  root "home#index"
  resources :divisions
  resources :targets
  resources :teams
  resources :employees
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/division.rb
class Division < ApplicationRecord
    belongs_to :employee
    has_many :team

    validates :name, presence: true
    validates :description, presence: true, length: { maximum: 30 }

    accepts_nested_attributes_for :team
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  before_action :set_division, only: %i[ show edit update destroy ]

  # GET /divisions or /divisions.json
  def index
    @divisions = Division.all
  end

  # GET /divisions/1 or /divisions/1.json
  def show
  end

  # GET /divisions/new
  def new
    @division = Division.new
    1.times { @division.team.build }
  end

  # GET /divisions/1/edit
  def edit
  end

  # POST /divisions or /divisions.json
  def create
    @division = Division.new(division_params)

    respond_to do |format|
      if @division.save
        format.html { redirect_to division_url(@division), notice: "Division was successfully created." }
        format.json { render :show, status: :created, location: @division }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /divisions/1 or /divisions/1.json
  def update
    respond_to do |format|
      if @division.update(division_params)
        format.html { redirect_to division_url(@division), notice: "Division was successfully updated." }
        format.json { render :show, status: :ok, location: @division }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @division.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /divisions/1 or /divisions/1.json
  def destroy
    if @division.team.present? 
      @division.team.each do |t|
        Team.destroy(t.id)
      end
    end

    @division.destroy
    
    respond_to do |format|
      format.html { redirect_to divisions_url, notice: "Division was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_division
      @division = Division.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def division_params
      params.require(:division).permit(:name, :description, :employee_id, team_attributes: [:id, :name, :description, :team_lead, :division_id])
    end
end

app/helpers/divisions_helper.rb
module DivisionsHelper
end

app/views/divisions/_division.html.erb
<div id="<%= dom_id division %>">
  <p>
    <strong>Name:</strong>
    <%= division.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= division.description %>
  </p>

  <p>
    <% if division.team.count > 0 %>
      <strong>Teams:</strong>
       <% division.team.each do |team| %>
              <%= team.name  %><span>, </span>
        <% end %> 
    <% end %>  
  </p>

  <p>
    <% if division.employee.present? %>
      <strong>Manager:</strong>
              <%= division.employee.name  %><span>
    <% end %>  
  </p>

</div>

app/views/divisions/_form.html.erb
<%= form_with(model: division) do |form| %>
  <% if division.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(division.errors.count, "error") %> prohibited this division from being saved:</h2>

      <ul>
        <% division.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :manager, style: "display: block" %>
    <%= form.select :employee_id, Employee.all.collect{ |employee| [" #{employee.name}",employee.id] }, prompt: "Choose one.." %>
  </div>

<%= form_with model: @division do|form|%>  
  Teams:
  <ul>
    <%= form.fields_for :team do |team_form| %>
      <li>
        <%= team_form.label :name, style: "display: block" %>
        <%= team_form.text_field :name %>
        <%= team_form.label :description, style: "display: block" %>
        <%= team_form.text_area :description %>
        <%= team_form.label :team_lead, style: "display: block" %>
        <%= team_form.select :team_lead, Employee.all.collect{ |employee| ["#{employee.name}",employee.name] }, prompt: 'Choose one...' %>
        </li>
      <div>
       <%= team_form.submit %>
     </div>
    <%end%>
  </ul>
 <%end%>

 


<% end %>

app/views/divisions/edit.html.erb
<h1>Editing division</h1>

<%= render "form", division: @division %>

<br>

<div>
  <%= link_to "Show this division", @division %> |
  <%= link_to "Back to divisions", divisions_path %>
</div>

app/views/divisions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Divisions</h1>

<div class="btn btn-info newbtn">
<%= link_to "New division", new_division_path %>
</div>

<br>
<br>
<div id="divisions">
<table class="table table-striped">
<thead class="thead-dark">
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Description</th>
    <th>Teams</th>
    <th>Manager</th>
    <th>Action</th>
  </tr>
<tbody>

  <% @divisions.each do |division| %>
  <tr>
    <td><%= division.id%></td>
    <td><%= division.name%></td>
    <td><%= division.description%></td>
    <% if division.team.count > 0 %>
     <td>
        <% division.team.each do |team| %>
              <%= team.name  %><span>, </span>
        <% end %> 
      </td>
    <%end%> 
    <% if division.employee.present? %>
      <td><%= division.employee.name%></td>
    <%end%>  
    <td class="actions">
      <%= link_to "Edit", edit_division_path(division) %> 
      <%= button_to "Delete", division, method: :delete %>
    </td>
  </tr>
  <% end %>
    </thead>
  </table>
</div>


<br>
<div class="btn">
<%= link_to "Back to home", "/" %>
</div>

app/views/divisions/new.html.erb
<h1>New division</h1>

<%= render "form", division: @division %>

<br>

<div>
  <%= link_to "Back to divisions", divisions_path %>
</div>

app/views/divisions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @division %>

<div>
  <%= link_to "Edit this division", edit_division_path(@division) %> |
  <%= link_to "Back to divisions", divisions_path %>

  <%= button_to "Destroy this division", @division, method: :delete %>
</div>