config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'home/index'
  root "home#index"
  resources :divisions
  resources :targets
  resources :teams
  resources :employees
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/_footer.html.erb
<div class="footer">
    <p>Copyright @ 2022 - Sprints - author: Mohanned , e-mail: makbar@mrsool.co </p>
</div>

app/views/layouts/_sidenav.html.erb
<div class="sidenav">
    <%= link_to "Employees", employees_path%>
    <%= link_to "Divisions", divisions_path%>
    <%= link_to "Teams", teams_path%>
    <%= link_to "Targets", targets_path%>
    <%= link_to "Users", users_path%>
</div>

app/views/layouts/_topnav.html.erb
<div class="topnav">
    <a href="#">HR Admin Platform</a>
    <div class="links">
        <% if current_user.present? %>
        <a href="#"><%= current_user.name %></a>
        <%= link_to  (t("Sign out")), destroy_user_session_path %>
        <%end%>
        <% if current_user.to_s.blank? %>
        <%= link_to  (t("Sign in")), new_user_session_url %>
        <%end%>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HRSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= stylesheet_link_tag "bootstrap", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "bootstrap", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/topnav" %>
    <div class="app_container">
      <%= render "layouts/sidenav" %>
      <div class="tableContent">
          <%= yield %>
      </div>
      
    </div>
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= render "layouts/footer" %>
  </body>
</html>